name: on Pull Request

on: # Every job to have separate if statement  
  pull_request:

jobs:
  do-something:
    name: Do something job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: First step 
        id: step-one
        continue-on-error: true
        run: |
          echo Foo
      
      - name: Second step 
        id: step-two
        continue-on-error: true
        run: |
          echo Bar
      
      - name: Third step 
        id: step-three
        continue-on-error: true
        run: |
          echo Baz
      
      - name: Get context 
        run: echo '${{ toJSON(github) }}'

      - name: Get head_ref 
        run: echo '${{ github.head_ref }}'
   
      - name: Get result 1
        run: echo "${{steps.step-one.outcome}}"
      
      - name: Get result 2
        run: echo "${{steps.step-one.outputs}}"

      - name: Get result 3
        run: echo "${{steps.step-one.conclusion}}"

      - uses: actions/github-script@v6
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"

  do-something-more:
    name: Do something job
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: First step 
        id: step-one
        run: |
          echo Foo
  
  do-something-more-again:
    name: Do something job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      status: ${{ steps.step-three.outputs.job_status }}
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: First step
        id: one
        continue-on-error: true 
        run: |
          echo Foo
          exit 1

      - name: Print status
        id: step-three
        run: echo "job_status='${{ steps.one.outcome }}'" >> $GITHUB_OUTPUT
        # if: ${{ steps.step-one.outcome }} != 'success'
  
  do-something-different:
    name: Do something job
    needs:
      - do-something
      - do-something-more
      - do-something-more-again

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Write brief job summary as comment to PR
      - name: Get context 
        run: echo '${{ toJSON(github) }}'
      
      - name: Get context 
        run: echo ${{needs.do-something.result}}
      
      - name: Get context 
        run: echo ${{needs.do-something-more.result}}
      
      - name: Get context 
        run: echo ${{needs.do-something-more-again.result}}

      - name: Get context 
        run: echo ${{needs.do-something-more-again.outputs}}
      
      - name: Get context 
        run: echo ${{toJSON(needs.do-something-more-again.outputs)}}

      - name: Get context 
        run: echo ${{needs.do-something-more-again.outputs.FOO}}
      
      - name: Get context 
        run: echo ${{needs.do-something-more-again.outputs.STATUZ}}
      
      # - name: Comment issue
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const output = `## Feature check
      #       #### First check 💼 \`${{ jobs.do-something.result }}\`
      #       #### Second check 🔑 \`${{ jobs.do-something-more.result }}\`
      #       #### Third check 🚀 \`${{ jobs.do-something-more-again.result }}\`
      #       `;
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: output
      #       })
      
      - name: Check for failed steps
        if: steps.step-one.outcome == 'failure' || steps.step-two.outcome == 'failure' || steps.step-three.outcome == 'failure'
        run: exit 1

  foo:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      status: ${{ steps.check-status.outputs.job_status }}
    steps:
    - id: step
      continue-on-error: true
      run: |
        echo foo
        exit 1
    
    - name: Check job status
      id: check-status
      run: echo "job_status='${{ steps.step.outcome }}'" >> $GITHUB_OUTPUT
    
  bar:
    runs-on: ubuntu-latest
    needs: foo
    steps:
    - run: echo ${{ needs.foo.outputs.status }}
    
    - run: echo ${{ toJSON(needs.foo.outputs) }}
      continue-on-error: true

  
    - name: Comment issue
      uses: actions/github-script@v6
      with:
        script: |
          const output = `## Feature check
          #### First check 💼 \`${{ needs.foo.outputs.status }}\`
          `;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })