name: on Pull Request

on:
  push:
    branches:
      - master

jobs:
  do-something:
    name: Do something job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: First step 
        id: step-one
        continue-on-error: true
        run: |
          echo Foo
      
      - name: Second step 
        id: step-two
        continue-on-error: true
        run: |
          echo Bar
      
      - name: Third step 
        id: step-three
        continue-on-error: true
        run: |
          echo Baz
      
      - name: Get context 
        run: echo '${{ toJSON(github) }}'

      - name: Get head_ref 
        run: echo '${{ github.head_ref }}'
   
      - name: Get result 1
        run: echo "${{steps.step-one.outcome}}"
      
      - name: Get result 2
        run: echo "${{steps.step-one.outputs}}"

      - name: Get result 3
        run: echo "${{steps.step-one.conclusion}}"

      - uses: actions/github-script@v6
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"

      # Write brief job summary as comment to PR
      - name: Comment issue
        uses: actions/github-script@v6
        with:
          script: |
            const output = `## Feature check
            #### First check 💼 \`${{ steps.step-one.outcome }}\`
            #### Second check 🔑 \`${{ steps.step-two.outcome }}\`
            #### Third check 🚀 \`${{ steps.step-three.outcome }}\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      - name: Check for failed steps
        if: steps.step-one.outcome == 'failure' || steps.step-two.outcome == 'failure' || steps.step-three.outcome == 'failure'
        run: exit 1