name: Testing pipeline

on:
  release:
    types:
      - created

jobs:
  do-something:
    name: Do something job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: First step 
        id: step-one
        continue-on-error: true
        run: |
          echo Foo
      
      - name: Second step 
        id: step-two
        continue-on-error: true
        run: |
          echo Bar
      
      - name: Third step 
        id: step-three
        continue-on-error: true
        run: |
          echo Baz
      
      - name: Get context 
        run: echo '${{ toJSON(github) }}'